### ISSUE TITLE
None of the public structs under irc::client implement the Debug trait.

### ISSUE THREAD

**Issue by iptq** [aatxe/irc#104]

**Comment by aatxe** [comment]
Is there anything in particular that you want out of the Debug implementations? It'd be useful for me to understand what the application is here. The default Debug definition would be essentially useless, I think.

**Comment by iptq** [comment]
So far, there's nothing in particular that I need yet. I'm just using a wrapper struct around IrcServer that implements Debug, but it won't compile since IrcServer doesn't implement Debug.

I looked at what IrcServer has, and it does seem kind of worthless to use the default Debug implementation since that'd recursively dump tons of Arcs, RwLocks and Mutexes, at the least. But I do think it'd be good to at least implement the trait and give a bit of information about the current state.
