### ISSUE TITLE
Remove Contributor Covenant

### ISSUE THREAD

**Issue by JohnMH** [aatxe/irc#108]
The Contributor Convenant is harmful in general to Free (Libre)/Open Source projects, especially as the document itself is far-reaching, and has in the past been used to 'out' a contributor who posted content the creators of the Contributor Convenant disagreed with on a personal account, unrelated to the project in question.

Instead, just use your own judgement to gauge whether or not something is welcome in your project, and if you have trouble with somebody act as you desire to handle it.

**Comment by retep998** [comment]
Having a code of conduct only serves to codify how the maintainer of the project would moderate their community regardless. The presence of a code of conduct does not have any effect on whether a potentially malicious moderator can target a person that they disagree with, but it *does* ensure that people are aware the community has a certain standard for behavior which they ought to uphold.

**Comment by aatxe** [comment]
I am comfortable with the code of conduct as it is suggestive of how my own judgment will be applied, and explicitly states the unwelcomeness of harassment in this space.

**Comment by TheMightyBuzzard** [comment]
Wasn't aware you used the Contributor Covenant. Sorry but I won't be contributing anymore. I dislike politics in my OSS.

**Comment by JohnMH** [comment]
@TheMightyBuzzard That is actually a great point as well, which I didn't think would matter. Software is about code, not ideology.

**Comment by retep998** [comment]
Is codifying the fact that you shouldn't harass other people really an ideological or political matter?

**Comment by TheMightyBuzzard** [comment]
@retep998 I don't mind having a code of conduct something along the lines of "Don't be a douchebag" but the CC is extremely political.

**Comment by aatxe** [comment]
It is the view of this project's maintainers that enforcing a community free of harassment is of the utmost importance, and your view that that is political will not change it.
