### ISSUE TITLE
Track actual nickname

### ISSUE THREAD

**Issue by panicbit** [aatxe/irc#125]
`IrcClient::current_nickname` currently only reports a nickname from the config.
It would make sense to track the actual nick (which could be different from any nick in the config e.g. caused by the server forcing a different nick).

**Comment by 8573** [comment]
I note that, though commit 0235c71268959f65f7190f52b91ec989355a46b5 may have fixed this issue, [that commit seems to have been reverted accidentally](https://github.com/aatxe/irc/commit/0235c71268959f65f7190f52b91ec989355a46b5#r30703035).

**Comment by panicbit** [comment]
Thanks :heart:

**Comment by 8573** [comment]
Hm, why does GitHub see this as closed by commit 0235c71268959f65f7190f52b91ec989355a46b5 *now*, "five hours ago", when that commit is over a year old and the latest merge to the main branch (or any branch) is from last year?

**Comment by panicbit** [comment]
GitHub :heart:

**Comment by aatxe** [comment]
I was doing some migration to a new machine, and I messed up and advanced develop to the point of 0.14, it seems. On the flip side, I think this might've fixed the mistake I made a while back where I accidentally reverted the commit. So, maybe it's not all bad?

**Comment by Ep0chalypse** [comment]
It looks like there has been a regression.

I'm using version 0.15.0 and `client.current_nickname()` returns the nickname from the config file which is not the actual nickname the bot is using. The irc server I'm connecting to is truncating the nickname when I connect.
