### ISSUE TITLE
strip IRC colors (bold, underline, etc.)

### ISSUE THREAD

**Issue by freddyb** [aatxe/irc#130]
I would like to implement a utility function that strips IRC colors. 
Where would you suggest this to be implemented?

**Comment by aatxe** [comment]
Good idea! I'm sure this would be useful for others as well. I would probably implement it similar to the way [ChannelExt](https://docs.rs/irc/0.13.5/irc/proto/chan/trait.ChannelExt.html) is implemented. That is, we could provide an extension trait for `String` that adds something like `strip_irc_formatting` which does what you suggest.
