### ISSUE TITLE
CertFP support

### ISSUE THREAD

**Issue by SuperManifolds** [aatxe/irc#131]
Add support for authenticating via a client SSL certificate.
I believe this could be implemented by passing a certificate to the identity function of TlsConnectorBuilder.

**Comment by SuperManifolds** [comment]
As I need this feature for my own use, I plan to implement it myself, but I wanted to make sure you would want this in the main library if I PR'ed

**Comment by aatxe** [comment]
Sounds good to me! CertFP seems to be common on major networks and clients. So, it's fitting. 😄
