### ISSUE TITLE
re-use existing Core?

### ISSUE THREAD

**Issue by freddyb** [aatxe/irc#139]
I'm writing an irc bot that's supposed to spawn multiple client connections, i.e., multiple IrcReactors.
Hence, I'd like to reuse a `tokio::Core`.

I'm happy to implement this in a pull request, but what's the preferred way:

Should I just make the fields `inner` and `handle in `IrcReactor` public and create it like so
```rust
let myreactor =  IrcReactor { ... }
```

or should I rewrite `IrcReactor::new()` to optionally take a core parameter?

**Comment by freddyb** [comment]
looking at https://github.com/aatxe/irc/blob/develop/src/client/reactor.rs#L42-L54

**Comment by aatxe** [comment]
I'm not quite sure I follow. `IrcReactor` is just a (thin) wrapper of `tokio::Core` already. If you just want to run connections to multiple servers on one `IrcReactor` (i.e. one `tokio::Core`), you can use `prepare_and_connect_server` (or prepare and connect separately) and `register_client_with_handler` for each connection you want on that reactor. You can see this pattern in the [multiserver example](https://github.com/aatxe/irc/blob/develop/examples/multiserver.rs#L26). 

If I'm misunderstanding what you mean, can you maybe elaborate a bit more with some pseudocode of the code you'd like to write?

**Comment by freddyb** [comment]
Ah, that makes sense. Nevermind. :roll_eyes:

**Comment by aatxe** [comment]
For some historical context: my original motivation in writing `IrcReactor` was that people kept telling me they were interested in using the async support, but "afraid of tokio." The library internals (mostly the transport) are actually where all of the "tricky parts" lie, and having `IrcReactor` seemed to help get people over the psychological hurdle.
