### ISSUE TITLE
Write a bot to actually run in continuous integration.

### ISSUE THREAD

**Issue by aatxe** [aatxe/irc#142]
It has happened a couple times now (thankfully not in a release version – at least, I don't think) that I've missed breakage that is specifically related to the code that connects to the internet. It would be really cool to have a bot setup that can be run as part of continuous integration to test that specific aspect. I'm sure it still won't catch everything that can go wrong, but it'll at least catch the obvious stuff. The bot should work as follows:

1. Connect to `irc.pdgn.co`via SSL with some username (idea: `irc-crate-ci`).
2. Join `#commits` which is our channel for commit bots and continuous integration.
3. Send a message like `Hello from Travis CI!`.
4. Send a QUIT message to the server and close out the connection (without error).

We can also do something similar without SSL (maybe to a Mozilla IRC channel? Pdgn requires SSL) during continuous integration.

**BONUS POINTS**: I think Travis sets some environment variables with info about the build being tested? It'd be cool if the message could include some of that info.

**Comment by aatxe** [comment]
As with most issues, I will try to get around to it myself, but I am even happier to help others get their first contributions in! So, if anyone wants to work on this, just ping me! 😄

**Comment by Bassetts** [comment]
@aatxe I am interested in picking this up, however I quite very new to Rust so was wondering if you could give me some guidance on getting started with this?

**Comment by aatxe** [comment]
@Bassetts Sorry, do you still need help? I saw some connections coming in already (and your other issue #158 seems related).

**Comment by Bassetts** [comment]
@aatxe I have made a start but still have a few questions. I was going to open a PR this evening in order to ask the questions with the context of what I have done so far.

**Comment by aatxe** [comment]
Okay, sounds great! Thanks! 😄
