### ISSUE TITLE
Do not require Handle in IrcClient::new_future

### ISSUE THREAD

**Issue by DoumanAsh** [aatxe/irc#150]
For some reason it is been added back on 0.14 branch

I believe it is no longer necessary with new tokio?
So should be removed?

**Comment by aatxe** [comment]
Yeah, something strange happened when I merged `develop` back into `0.14`. I don't expect `0.14` to drop in the immediate future, but I'll leave this open as a note about fixing it.

**Comment by DoumanAsh** [comment]
@aatxe so for now I shouldn't create PR to remove it? You'd prefer to remove it when `0.14` will be ready?

**Comment by aatxe** [comment]
If you’d like to submit a PR fixing 0.14, that would be appreciated! I’m quite busy until next week is over right now.

**Comment by DoumanAsh** [comment]
Ok, I'll do it on weekend, though I if you're planning further merges from develop branch I might hold on it to avoid getting it lost 😄

**Comment by aatxe** [comment]
Sounds good! Commit 53fb890a7e69d4fa65bba4c07dd46e32e71d3022 might prove useful (or at least the diff for it). That's where I messed it up and the old version before it has the newer tokio stuff.

**Comment by aatxe** [comment]
This was solved in #152.
