### ISSUE TITLE
irc 0.13.6 may panic on ping timeout

### ISSUE THREAD

**Issue by kpcyrd** [aatxe/irc#167]
I just noticed I still had a project running that was connected using the irc crate and apparently a thread panic'ed while switching networks during the day:
```
thread '<unnamed>' panicked at 'connection reset: no ping response', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/irc-0.13.6/src/client/mod.rs:707:41
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PingTimeout', libcore/result.rs:1009:5
```

The relevant code seems to be:
```rust
let outgoing_future = sink.send_all(rx_outgoing.map_err::<error::IrcError, _>(|_| {
    unreachable!("futures::sync::mpsc::Receiver should never return Err");
})).map(|_| ()).map_err(|e| panic!("{}", e));

```

**Comment by aatxe** [comment]
This is expected if you're using the old API (`IrcClient::from_config` and `IrcClient::new`). As far as I can tell, there's no obvious way to resolve this with that API setup, but if you use the `IrcReactor` API (or `IrcClient::new_future`) directly, as shown in [the README](https://github.com/aatxe/irc#reactors-the-new-api), these errors should bubble out from `IrcReactor::run` and thus can be handled by user code.
