### ISSUE TITLE
Bump tokio and move to std Future (async/await)

### ISSUE THREAD

**Issue by udoprog** [aatxe/irc#182]
I've been tinkering with bumping this crate to the upcoming std future and tokio to make sure it's ready when both are released.

My thinking here would be to:
* Get rid of the reactor. Using async functions and blocks directly is more ergonomical than using callbacks.
* Convert all existing futures and streams in place first, then see if there's any opportunities to improve APIs.

I was hoping to track progress here.

**Comment by 8573** [comment]
> Using async functions

This would mean raising the minimum required Rust version, right?

**Comment by udoprog** [comment]
@8573 Yes. As well as a major API break.

**Comment by udoprog** [comment]
Started working on it here:
https://github.com/udoprog/irc/tree/tokio-bump

I did an initial pass where I tried to maintain the existing API, but it didn't make much sense to me.
* Dropped the use of `ClientExt` in favor if tiny bit of duplication in `ClientState`.
* Renamed `IrcClient` to `Client`.
* Renamed `PackedIrcClient` to `PackedClient`.
* Renamed `error::IrcError` to `error::Error`.
* `mockstream` is not up-to-date with unstable tokio, so had to drop that for now. Tests don't run until that has been implemented.
* Removed most things associated with the reactor.
* `ClientStream` drives the stream for outgoing messages by default, unless it has been taken from the `Client` through `Client::outgoing`.
* You can access a thread-safe sender through `Client::sender`, which uses the outgoing queue for sending messages.
* Switched mutexes and locks to use [`parking_lot`](https://github.com/Amanieu/parking_lot).

You can see the new API in-use in the [`build-bot`](https://github.com/udoprog/irc/blob/tokio-bump/src/bin/build-bot.rs) bin. ~~I'm considering making the send future part of the client stream instead of having it be a separate thing. Alternative have it be a thing that can be taken out of the client similarly to how `stream` is right now.~~ This is done.

Examples ported:
* [multiserver](https://github.com/udoprog/irc/blob/tokio-bump/examples/multiserver.rs)

**Comment by udoprog** [comment]
Done since #184 was merged
