### ISSUE TITLE
file descriptor leak

### ISSUE THREAD

**Issue by thepixelmonk** [aatxe/irc#183]
Making an irc connection seems to create a few dangling file descriptors that aren't cleaned up when the thread closes as far as I can tell. Could be an issue for long-running programs like mine that manage many irc connections at once, and reconnect as needed. My file descriptor count just keeps slowly increasing.

**Comment by aatxe** [comment]
Can you clarify which style of API you're using? This sounds like you're using the older API anyway, which will eventually go away when tokio 0.2 is finally released (see: #182 and #184).

**Comment by thepixelmonk** [comment]
Yeah older api.

**Comment by aatxe** [comment]
The next release wouldn't support the old API. So, I'm marking this as won't fix.
