### ISSUE TITLE
Reading Private Chat messages

### ISSUE THREAD

**Issue by Ap0ph1s** [aatxe/irc#20]
How do I go about reading input from Private chats?

**Comment by aatxe** [comment]
Getting messages from a query (or private message) works exactly like getting messages from a channel. The only difference is that the target (or first argument) of the private message will be the name of the bot. Here's some examples.

```rust
extern crate irc;

use std::default::Default;
use irc::client::prelude::*;

fn main() {
    let server = IrcServer::from_config(Default::default()).unwrap(); // you'll need a real configuration here.
    server.identify().unwrap();
    for message in server.iter() {
        let message = message.unwrap(); // We'll just panic if there's an error.
        if &message.command[..] == "PRIVMSG" {
            if let Some([target]) = message.args {
                if target == server.config().nickname() {
                    // It must be a private message!
                    // message.get_source_nickname() will return an option containing the sender's nickname.
                }
            }
        }
    }
}
```

**Comment by filipegoncalves** [comment]
Side-note: To do this you must really use `server.iter()` and not `server.iter_cmd()`. As of now, the internal conversion from `Message` to `Command` drops the prefix, so you lose the source nickname. This should be fixed soon though.

`message.get_source_nickname()` will give you the source of the message. To get the actual message text, use `message.suffix`.

**Comment by Ap0ph1s** [comment]
Thanks!
