### ISSUE TITLE
Possible to get channel mode?

### ISSUE THREAD

**Issue by nuxeh** [aatxe/irc#200]
Hi, is there any way to get channel modes using the `irc` crate?

The following returns `Result<()>` so guessing it doesn't allow for this...
https://docs.rs/irc/0.13.6/irc/client/ext/trait.ClientExt.html#method.send_mode

If not, any thoughts on how feasible this would be to implement?

Thanks!

**Comment by aatxe** [comment]
The method you linked is a way of sending a command to the server to _change_ modes. If you would like to know what modes are associated with a channel, you have to query the server and get back a response of [this form](https://docs.rs/irc/0.13.6/irc/proto/command/enum.Command.html#variant.ChannelMODE).

**Comment by nuxeh** [comment]
Ok, thanks... but how would such a response be elicited from the server using this crate?

The `send_mode` function can't be used without providing an array of `ModeType`, and doesn't like an empty array slice.

Is this something that needs implementing to achieve, or have I missed something obvious?

**Comment by nuxeh** [comment]
I say this since, as far as i'm aware, to query a channel's modes you would normally send `/mode #channel`, i.e. the mode command with no mode parameters.
