### ISSUE TITLE
Default ping timeout too low to connect to freenode

### ISSUE THREAD

**Issue by FauxFaux** [aatxe/irc#207]
When connecting to Freenode, from a machine without working reverse dns (like my home), the crate returns a phantom PingTimeout error exactly 10s after start. It appears to have finished connecting, has received the motd and is receiving user modes and the like, but then just PingTimeouts.

Raising the `ping_timeout:` to `Some(20)` fixes this; it gives the server enough time to reply to our startup ping (I guess? The sending of pings doesn't seem to be logged.)

Please raise the default ping timeout, and/or have an allowance for starting the ping timeout timer after we are connected; perhaps ignoring the ping/pong (with weird token) some servers do before they send the motd?

**Comment by aatxe** [comment]
This should've been resolved in #222.
