### ISSUE TITLE
How to ignore certificate verification? 

### ISSUE THREAD

**Issue by kevinpostal** [aatxe/irc#209]
How do you connect without validating the cert?

**Comment by quite** [comment]
I've been maintaining the following fork which adds an `insecure` option for that. It's not a great idea but... https://github.com/quite/irc

I was just looking at jumping onto irc 0.14.0 for that. ~~But I can't get my patch to work!~~ I does work (branch `newer`).

But, I'd be happy to use `cert_path` to pass the certificate of the server I want to connect to, but I can't get that to work, it won't verify.

**Comment by simnalamburt** [comment]
I've made a PR for this issue, using @quite's patch: https://github.com/aatxe/irc/pull/236



###### References
- https://docs.rs/native-tls/0.2.1/native_tls/struct.TlsConnectorBuilder.html#method.danger_accept_invalid_certs
- https://docs.rs/rustls/0.19.0/rustls/struct.ClientConfig.html#method.dangerous
- https://docs.rs/rustls/0.19.0/rustls/struct.DangerousClientConfig.html#method.set_certificate_verifier
- https://github.com/quite/irc/commit/a609e4e72cad6c8e649fabeee9c42443ec36cecc

**Comment by quite** [comment]
@simnalamburt  thank you, wouldn't mind having this for sure :)

**Comment by quite** [comment]
@aatxe great! how about a new release? :)
