### ISSUE TITLE
Broken link in docs in irc crate where irc_proto is pulled in 

### ISSUE THREAD

**Issue by BlueSpaceCanary** [aatxe/irc#210]
Just a small docs nit I noticed: the link at https://github.com/aatxe/irc/blob/67e61e06060e2fde1435c724114af0087555c3cd/irc-proto/src/message.rs#L16 is broken when viewed in the `irc` crate [docs](https://docs.rs/irc/0.14.0/irc/client/prelude/struct.Message.html), because in `irc` both `Message` and `Command` are directly members of `client::prelude`

**Comment by aatxe** [comment]
Is there a strategy for dealing with these kinds of issues? Surely, there ought to be a way to produce the link using the Rust full path to Command instead of this, but I don't know of such a thing.

**Comment by aatxe** [comment]
This should be fixed now.
