### ISSUE TITLE
tokio 0.3 / tokio-codec 0.5

### ISSUE THREAD

**Issue by martinetd** [aatxe/irc#224]
FWIW tokio released a semi-major update recently-ish.

I tried updated my program but the IrcCodec provided with older tokio-codec wasn't compatible (see https://github.com/tokio-rs/tokio/discussions/3081 )

I didn't manage to wrap it properly as suggested :/ so will just wait until the irc crate updates at some point, might be worth tracking :)

**Comment by martinetd** [comment]
doh, I'm blind -- somehow screwed up my refresh and missed it's been done (well, irc-codec is still 0.4 but I need to try again with that)

Closing :)

**Comment by aatxe** [comment]
No worries! :)
