### ISSUE TITLE
`Custom` command

### ISSUE THREAD

**Issue by kgv** [aatxe/irc#23]
It would be great to add `Custom` (`Raw`) command to `enum Command`. Or make possible execute `from_message` method for custom message:

```rust
let message = Message {
    prefix: None,
    command: "CUSTOM_COMMAND".to_string(),
    args: vec!["arg0".to_string()],
    suffix: None,
};
let custom_command = Command::from_message(&message).unwrap();
```

thx.

**Comment by aatxe** [comment]
Do you have a particular use case in mind for this?

**Comment by kgv** [comment]
For example: twitch.tv irc chat need [use](http://discuss.dev.twitch.tv/t/accessing-chat-information/307) custom command `TWITCHCLIENT`

**Comment by aatxe** [comment]
So, you only need to be able to send custom commands, right?

**Comment by aatxe** [comment]
I've made some changes to the interface for `Server`. `send(...)` now takes a `ToMessage` type, and not strictly a `Command`. So, you can send the command using either a `Message` as shown above, or very simply as a string (there's an `&str` impl for `ToMessage`). Does that work for you?

**Comment by aatxe** [comment]
Well, things changed a little bit more now and I replaced `ToMessage` with `Into<Message>` but it's the same idea.

**Comment by kgv** [comment]
Trait `Into<Message>` (`ToMessage`) for method `Server. send(...)` is good idea. Thanks.
