### ISSUE TITLE
Release 0.15.1

### ISSUE THREAD

**Issue by simnalamburt** [aatxe/irc#251]
I'm still waiting for https://github.com/aatxe/irc/pull/236 to be released, so that I don't need to use forked version. It's been two years since the last release, so please release the new one.

**Comment by whatakey** [comment]
is this project dead?

**Comment by simnalamburt** [comment]
The maintainer is actually reviewing some PRs periodically. It’s just v0.15.1 not released yet.

**Comment by whatakey** [comment]
nice, I hope there's an update soon :)

**Comment by aatxe** [comment]
Yeah, sorry, I've not been the best maintainer for this project in recent times since I have a full-time job doing other OSS work, and I don't even use IRC anymore, but I'm going to do a new release today.

**Comment by simnalamburt** [comment]
Wow! 1.0.0 has been released! Thanks!

###### References
- https://crates.io/crates/irc/1.0.0

**Comment by aatxe** [comment]
Yeah, figured it was about time and I had a conversation with someone about the broad frustration of so much of the Rust ecosystem still being `0.x.x` despite having not changed APIs in years. Figured I ought to at least do my part to make things better.
