### ISSUE TITLE
Send time limit

### ISSUE THREAD

**Issue by Vikaton** [aatxe/irc#27]
Is there something that is throttling sent messages if they are sending to fast, if so, how can I turn it off?

**Comment by aatxe** [comment]
No, there is no client-side message throttling other than a mutex preventing multiple sends at the same time.

**Comment by Vikaton** [comment]
That could possibly be what I'm looking for, is there a way to disable the mutex?

**Comment by aatxe** [comment]
No, the library would then no longer be thread-safe.

**Comment by Vikaton** [comment]
Ok, thanks
