### ISSUE TITLE
ERR_KEYNOPERMISSION Typo/Bug

### ISSUE THREAD

**Issue by crespyl** [aatxe/irc#38]
I was just skimming the source and noticed that in [response.rs](https://github.com/aatxe/irc/blob/master/src/client/data/response.rs#L344-L345) `ERR_KEYNOPERMISSION` is defined as 779, but the preceding comment describes it with 769.

I'm not sure which is correct, but at least one is probably wrong.

**Comment by aatxe** [comment]
Ah, good catch. The correct definition should be 769. Thanks!

**Comment by aatxe** [comment]
I fixed this in 6e160f561f5b9d49069def3efb7c0654764b07d9.
