### ISSUE TITLE
extreme CPU usage on OS X

### ISSUE THREAD

**Issue by tahnok** [aatxe/irc#43]
Hello!

I'm trying to write a little bot in IRC, but when I run my really simple bot (it just says "hi" to anything) it takes up a whole core worth of CPU!

Details about my system:
 - platform: OS X 10.10.5
 - rust version: `rustc 1.6.0 (c30b771ad 2016-01-19)`

Source code for the offending bot: https://github.com/tahnok/ironbot/blob/master/src/main.rs

Has anyone else seen this? Is it just an OS X thing?

**Comment by aatxe** [comment]
Ah, this is a very interesting catch. I'm experiencing the same problem on OS X. I never noticed because I always do hosting on Linux! I'll investigate further.

**Comment by retep998** [comment]
It doesn't occur to me on Windows. Probably is just an OS X thing.

**Comment by bruceg** [comment]
I also see this problem on Linux. Doing a strace on the child thread shows the program doing an endless loop doing stat on /etc/localtime

**Comment by aatxe** [comment]
Ah, good catch. I think I know what the problem is.
