### ISSUE TITLE
Non-channel PRIVMSG message has wrong name

### ISSUE THREAD

**Issue by bruceg** [aatxe/irc#44]
When receiving a message from a channel, the resulting PRIVMSG command has the channel as the msgtarget parameter. However, when receiving a private message, the msgtarget parameter contains the bot's nick instead of the sender's nick. This makes direct replies impossible.

**Comment by aatxe** [comment]
It does not have the wrong name. The target of the message was indeed the receiver, not the sender. This is just how the protocol works. If you want to get the sender's nickname, you can use `source_nickname()` on [Message](http://aatxe.github.io/irc/irc/client/data/message/struct.Message.html). The typical pattern is something like the following:
```rust
let resp = if target.starts_with("#") {
  target
} else if let Some(src) = msg.source_nickname() {
  src
} else {
  // you could panic or do a default or something.
}
```

**Comment by bruceg** [comment]
That's kinda awkward, though I guess it fits with the protocol. I had thought the library I am trying to port from just provided the sender name in the privmsg callback, but I see now it doesn't either.

**Comment by aatxe** [comment]
It might be worth adding something like `response_target()` to Message that if the message was a PRIVMSG or NOTICE would return the target if it was a channel or the source nickname otherwise. What do you think?

**Comment by bruceg** [comment]
A helper function would be useful, yes, but not strictly needed. I may not even end up using it.
