### ISSUE TITLE
Config file channel keys

### ISSUE THREAD

**Issue by bajr** [aatxe/irc#51]
I couldn't find a way to easily autojoin channels that need a channel key. Maybe these chankeys could be read from the config file somehow?

**Comment by elifoster** [comment]
I have thought of two ideas for this.

1. Change `channels` to a hash, so it'd look like:
```json
"channels": {
  "#rust": "",
  "#secretchannel": "supersecretpassword"
}
```

2. Create a separate channel key hash:
```json
"channels": ["#rust", "#secretchannel"],
"channelkeys": {
  "#secretchannel": "supersecretpassword"
},
```

2 is much better in my opinion, as it requires no changes for people who aren't using channels with keys, and it's much more readable and obvious.

**Comment by aatxe** [comment]
Yeah, I'm going to say that #2 is probably the best option because channels without keys simply won't have keys rather than having blank ones.
