### ISSUE TITLE
update openssl version

### ISSUE THREAD

**Issue by hikilaka** [aatxe/irc#62]
I have ran into some issues using the irc crate in my project, it seems to use an outdated version of openssl-sys (specifically version 0.7; current version is 0.9.5).

Here is the error message I am getting when using this in conjunction with curl (uses up-to-date version of openssl-sys.

`Updating registry `https://github.com/rust-lang/crates.io-index
 Downloading curl v0.4.2
 Downloading curl-sys v0.3.6
 Downloading libz-sys v1.0.10
 Downloading openssl-sys v0.9.5
 Downloading openssl-probe v0.1.0
 Downloading metadeps v1.1.1
 Downloading error-chain v0.7.2
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.7.17
  openssl-sys v0.9.5

shell returned 101

Press ENTER or type command to continue
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.9.5
  openssl-sys v0.7.17

shell returned 101

Press ENTER or type command to continue
`

**Comment by aatxe** [comment]
While this would be ideal, this is unfortunately non-trivial. `try_clone()` has been removed from the SslStream interface, and was important in the implementation of Connections. The reasons for this removal are legitimate (sfackler/rust-openssl#338 and sfackler/rust-openssl#445), but it's not immediately clear to me the best way to proceed. However, I will work on it.

**Comment by themasch** [comment]
would this be a good chance to use a tls abstraction lib like [native-tls](https://github.com/sfackler/rust-native-tls)?

**Comment by aatxe** [comment]
Fixed in 02f9968b0cdc2754a0659bcd9f83fc5e2c5cd736. We'll look at `native-tls` et al. later.
