### ISSUE TITLE
encoding in privmsg

### ISSUE THREAD

**Issue by bayang** [aatxe/irc#69]
Hi,

I'm a newbie in Rust so it might be a stupid question, but,
I just tried to print in my terminal  the received Command::privmsgs in a chan and sometimes I get this kind of stuff : 
 ACTION blah blah 

my terminal is configured in UTF-8
Am I missing something obvious ?

**Comment by retep998** [comment]
That's a CTCP command. The encoding is fine.

**Comment by aatxe** [comment]
Indeed, the way CTCP works is that it uses null characters to contain the CTCP command. Typically, full IRC clients will choose to display these commands in different ways. For example, a CTCP ACTION might be displayed as `user blah blah`.

**Comment by bayang** [comment]
Ok right,

thank you both fo answering !

**Comment by FreeFull** [comment]
Just a quick correction, CTCP doesn't use null characters (and neither does any other part of the IRC protocol). The CTCP delimiters are the `0x01` character

**Comment by aatxe** [comment]
Oh whoops, you're right it's SOH, not null.
