### ISSUE TITLE
With the simple ssl example, why is the sent message not received by the client?

### ISSUE THREAD

**Issue by Borkason** [aatxe/irc#72]
Running this example: https://github.com/aatxe/irc/blob/master/examples/simple_ssl.rs

Every message is printed to the console, except for the "Hi!" reply. I'd like to understand why that message is not received by the client?

**Comment by aatxe** [comment]
This is an artifact of how the IRC protocol works. The server does not send you back messages you send, and thus, it never gets printed in this code. You could get around this by printing all sent messages. This could be something added as a configuration option, or compile-time flag.

**Comment by Borkason** [comment]
Thank you for the quick explanation.
