### ISSUE TITLE
IRC crate incorrectly interprets an ISUPPORT message as a BOUNCE message

### ISSUE THREAD

**Issue by sector-f** [aatxe/irc#87]
According to [this page](http://modern.ircdocs.horse/) (which, according to Havvy on the #rust IRC channel, "should be considered for all intents and purposes the living IRC specification"), `005` is `RPL_ISUPPORT`.

This crate incorrectly interprets `005` as `RPL_BOUNCE`. `005` *was* formerly `RPL_BOUNCE`, but that has been moved to `010`.

To fix this issue:

* `irc::client::data::response::Response` needs a `RPL_ISUPPORT` variant added, as it does not currently have one
* A response with a numeric of `005` should be interpreted as `RPL_ISUPPORT`
* A response with a numeric of `010` should be interpreted as `RPL_BOUNCE`

For reference, here are the two `ISUPPORT` messages I received from Rizon's IRC server when connecting to it:

```
:solenoid.rizon.net 5 ircfs CALLERID CASEMAPPING=rfc1459 DEAF=D KICKLEN=180 MODES=4 PREFIX=(qaohv)~&@%+ STATUSMSG=~&@%+ EXCEPTS=e INVEX=I NICKLEN=30 NETWORK=Rizon MAXLIST=beI:250 MAXTARGETS=4  :are supported by this server
:solenoid.rizon.net 5 ircfs CHANTYPES=# CHANLIMIT=#:500 CHANNELLEN=50 TOPICLEN=390 CHANMODES=beI,k,l,BCMNORScimnpstz WATCH=60 NAMESX UHNAMES AWAYLEN=180 ELIST=CMNTU SAFELIST KNOCK :are supported by this server
```

**Comment by aatxe** [comment]
Thanks, good catch!
