### ISSUE TITLE
`Command::JOIN`'s docs don't explain the last `Option<String>` field

### ISSUE THREAD

**Issue by niconii** [aatxe/irc#90]
[Link](https://github.com/aatxe/irc/blob/ec8fdeb/src/proto/command.rs#L33-L34)
```rust
    /// JOIN chanlist [chankeys]
    JOIN(String, Option<String>, Option<String>),
```
It looks like it's part of [this extension](http://ircv3.net/specs/extensions/extended-join-3.1.html), being for the `:Real Name` field, but it's a bit confusing when there's nothing to really explain this or what the extra field is for, besides a passing mention later on that JOIN has something to do with 3.1 extensions:
```rust
    // IRCv3.1 extensions
    ...
    // JOIN is already defined.
    // JOIN(String, Option<String>, Option<String>),
```

**Comment by aatxe** [comment]
That's exactly correct. I'll update the docs! Thanks!
