### ISSUE TITLE
current_nickname() is no longer exposed

### ISSUE THREAD

**Issue by sector-f** [aatxe/irc#91]
I noticed that as of version `0.12.0`, the `current_nickname()` function was no longer documented. I've found that it still exists (and is marked `pub`) under `impl ServerState`. 

I think the fix is making `ServerState::current_nickname()` private, and giving `IrcServer` a public method that calls `current_nickname()` on its `ServerState`.

**Comment by aatxe** [comment]
Ah, my bad. I got overzealous with moving things around. I'll fix this as soon as I can.
