### ISSUE TITLE
Strange encoding behaviour

### ISSUE THREAD

**Issue by ParadoxSpiral** [aatxe/irc#95]
When receiving the PRIVMSG `äöü`, the message content is `���`, while e.g. `高垣彩陽` is correctly transmitted. This happens on rizon, but not on freenode.

I don't have a small reproducer rn, but I encountered this while working on [an irc bot](https://github.com/ParadoxSpiral/parabot).

**Comment by aatxe** [comment]
Are you sure that you've configured the bot on Rizon to use the correct encoding for the server?

**Comment by ParadoxSpiral** [comment]
I think so, you mean [this](https://github.com/ParadoxSpiral/parabot/blob/master/src/config.rs#L90)?

**Comment by aatxe** [comment]
Yeah, are you sure that Rizon uses UTF-8? It sounds like it doesn't.

**Comment by ParadoxSpiral** [comment]
Well, if it didn't wouldn't the japanese characters also be wrong?
Sending `äöü` with e.g. Hexchat to other people works.

**Comment by aatxe** [comment]
I couldn't tell you. It's possible that the Japanese characters are the same in the encoding they use as UTF-8, but the one for umlauts are not.

**Comment by ParadoxSpiral** [comment]
Asked in #help, and they say that Rizon uses UTF-8.

**Comment by aatxe** [comment]
Well, I just attempted to send this message on Rizon using the bot in `example/simple.rs` and could not reproduce the bug.

**Comment by ParadoxSpiral** [comment]
Weird. Only changing the channel & server reproduces for me: `:ParadoxSpiral!~ParadoxSp@F6B8A582:9E72264:5D6CC095:IP PRIVMSG #parabot_testing :���`

**Comment by FreeFull** [comment]
I think some clients are broken and don't always send UTF-8 for all messages. I'm not sure why it wouldn't happen on freenode though.

**Comment by aatxe** [comment]
Yeah, that seems to be exactly what's happening. @ParadoxSpiral is using Xchat, and Xchat seems to be the common factor in messages that appear incorrectly.

**Comment by ParadoxSpiral** [comment]
Seems like it. We did some testing, and this only happens when my client (xchat, not hexchat) sends the message.
